"""
MindSense AI - Session Memory
================================
Stores session-level context: summaries, detected conditions,
risk history, and metadata for the current conversation session.

Bridges conversation memory (turn-level) and user memory (cross-session).

Usage::

    from memory.session_memory import SessionMemory
    session = SessionMemory(session_id="abc123")
    session.update_classification("Anxiety", 0.85)
    session.set_summary("User is experiencing work-related anxiety...")
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from utils.logger import get_logger
from utils.helpers import get_utc_timestamp

logger = get_logger(__name__)


class SessionMemory:
    """
    Session-level context manager for a single conversation session.

    Tracks the evolving clinical picture across turns within one session:
    detected conditions, risk levels, themes, and a generated summary.

    Attributes:
        session_id (str): Unique session identifier.
        user_id (str): User identifier (for cross-session memory linking).
        created_at (str): ISO timestamp of session creation.
    """

    def __init__(self, session_id: str, user_id: str = "anonymous") -> None:
        """
        Initialize a session memory instance.

        Args:
            session_id: Unique identifier for this session.
            user_id: User identifier (default "anonymous").
        """
        self.session_id: str = session_id
        self.user_id: str = user_id
        self.created_at: str = get_utc_timestamp()
        self.last_updated: str = get_utc_timestamp()

        # Clinical tracking
        self._classifications: List[Dict[str, Any]] = []  # Per-turn classification history
        self._risk_levels: List[str] = []                  # Per-turn risk history
        self._intents: List[str] = []                      # Per-turn intent history
        self._themes: List[str] = []                       # Accumulated themes
        self._crisis_triggered: bool = False

        # Session summary (generated by SummaryAgent)
        self._summary: Optional[str] = None

        # Dominant condition for the session
        self._dominant_label: Optional[str] = None
        self._dominant_confidence: float = 0.0

        logger.debug(f"SessionMemory initialized | session={session_id} | user={user_id}")

    def update_classification(self, label: str, confidence: float) -> None:
        """
        Record a new classification result for the current turn.

        Args:
            label: Predicted mental health label.
            confidence: Prediction confidence score.
        """
        entry = {
            "label": label,
            "confidence": confidence,
            "timestamp": get_utc_timestamp(),
        }
        self._classifications.append(entry)

        # Update dominant label if this is the most confident so far
        if confidence > self._dominant_confidence:
            self._dominant_label = label
            self._dominant_confidence = confidence

        self.last_updated = get_utc_timestamp()
        logger.debug(f"Classification updated | label={label} | conf={confidence:.3f}")

    def update_risk_level(self, risk_level: str) -> None:
        """
        Record the risk level for the current turn.

        Args:
            risk_level: Risk level string ("low", "moderate", "high", "critical").
        """
        self._risk_levels.append(risk_level)

        if risk_level in ("high", "critical"):
            self._crisis_triggered = True
            logger.warning(
                f"Crisis triggered in session {self.session_id} | risk={risk_level}"
            )

        self.last_updated = get_utc_timestamp()

    def update_intent(self, intent: str) -> None:
        """
        Record the detected user intent for the current turn.

        Args:
            intent: Intent string (e.g., "vent", "seek_advice", "crisis", "info").
        """
        self._intents.append(intent)
        self.last_updated = get_utc_timestamp()

    def add_themes(self, themes: List[str]) -> None:
        """
        Add newly detected themes to the session's theme pool.
        Deduplicates automatically.

        Args:
            themes: List of theme strings to add.
        """
        for theme in themes:
            if theme and theme not in self._themes:
                self._themes.append(theme)
        self.last_updated = get_utc_timestamp()

    def set_summary(self, summary: str) -> None:
        """
        Set the session summary generated by the SummaryAgent.

        Args:
            summary: Plain text session summary.
        """
        self._summary = summary.strip()
        self.last_updated = get_utc_timestamp()
        logger.debug(f"Session summary updated | session={self.session_id}")

    @property
    def summary(self) -> Optional[str]:
        """The current session summary string."""
        return self._summary

    @property
    def dominant_label(self) -> str:
        """The most confident mental health label seen in this session."""
        return self._dominant_label or "Normal"

    @property
    def current_risk_level(self) -> str:
        """The most recent risk level recorded in this session."""
        if not self._risk_levels:
            return "low"
        return self._risk_levels[-1]

    @property
    def highest_risk_level(self) -> str:
        """The highest risk level observed across all turns in this session."""
        risk_order = {"low": 0, "moderate": 1, "high": 2, "critical": 3}
        if not self._risk_levels:
            return "low"
        return max(self._risk_levels, key=lambda r: risk_order.get(r, 0))

    @property
    def current_intent(self) -> str:
        """The most recently detected user intent."""
        if not self._intents:
            return "general"
        return self._intents[-1]

    @property
    def themes(self) -> List[str]:
        """All unique themes detected across this session."""
        return list(self._themes)

    @property
    def crisis_triggered(self) -> bool:
        """Whether a crisis-level risk was triggered at any point in this session."""
        return self._crisis_triggered

    @property
    def turn_count(self) -> int:
        """Number of turns recorded in this session."""
        return len(self._classifications)

    def get_session_snapshot(self) -> Dict[str, Any]:
        """
        Get a full snapshot of the session state for memory persistence.

        Returns:
            Dictionary with all session metadata.
        """
        return {
            "session_id": self.session_id,
            "user_id": self.user_id,
            "created_at": self.created_at,
            "last_updated": self.last_updated,
            "turn_count": self.turn_count,
            "dominant_label": self.dominant_label,
            "dominant_confidence": round(self._dominant_confidence, 4),
            "highest_risk_level": self.highest_risk_level,
            "crisis_triggered": self.crisis_triggered,
            "themes": self.themes,
            "summary": self.summary,
            "classification_history": self._classifications[-5:],  # Last 5
            "risk_history": self._risk_levels[-5:],
        }
